# Generated by Django 5.2.3 on 2025-11-29 13:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hunters', '0002_migrate_to_gun_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('center_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('center_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radius_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('season_start', models.DateField()),
                ('season_end', models.DateField()),
                ('daily_start_time', models.TimeField()),
                ('daily_end_time', models.TimeField()),
                ('allowed_weekdays', models.CharField(default='1,2,3,4,5,6,0', help_text='Comma-separated weekday numbers (0=Monday, 6=Sunday)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmmunitionPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammo_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.CharField(max_length=200)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('used_quantity', models.PositiveIntegerField(default=0)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunters.hunter')),
            ],
        ),
        migrations.CreateModel(
            name='HunterLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('license_type', models.CharField(max_length=50)),
                ('issuing_authority', models.CharField(max_length=200)),
                ('max_daily_shots', models.PositiveIntegerField(default=50)),
                ('allowed_weapon_types', models.CharField(default='rifle,shotgun,bow', help_text='Comma-separated weapon types', max_length=200)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True)),
                ('hunter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='hunters.hunter')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('AMMO_EXCESS', 'Shot more ammunition than purchased'), ('ILLEGAL_ZONE', 'Shot in restricted/illegal area'), ('ILLEGAL_TIME', 'Shot outside permitted hours'), ('ILLEGAL_DATE', 'Shot outside hunting season'), ('UNLICENSED', 'Hunter license expired or invalid'), ('WEAPON_UNREGISTERED', 'Used unregistered weapon')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Minor infraction'), ('MEDIUM', 'Significant violation'), ('HIGH', 'Serious offense'), ('CRITICAL', 'Criminal activity suspected')], max_length=10)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('evidence_data', models.JSONField(blank=True, default=dict)),
                ('gun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hunters.gun')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunters.hunter')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hunters.shot')),
                ('hunting_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.huntingzone')),
            ],
        ),
    ]
