# Generated by Django 4.2.7 on 2025-11-23 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('sound', 'Sound Level'), ('vibration', 'Vibration'), ('gps', 'GPS Location'), ('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='offline', max_length=20)),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('firmware_version', models.CharField(default='1.0.0', max_length=20)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['location_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('sound', 'Sound Level'), ('vibration', 'Vibration'), ('gps', 'GPS Location'), ('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=20)),
                ('value', models.FloatField(help_text='Sensor reading value')),
                ('unit', models.CharField(help_text='Unit of measurement (dB, Hz, °C, etc.)', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('device_id', models.CharField(default='default_sensor', max_length=50)),
                ('battery_level', models.FloatField(blank=True, help_text='Battery percentage', null=True)),
                ('signal_strength', models.FloatField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_type', '-timestamp'], name='sensors_sen_sensor__6403aa_idx'), models.Index(fields=['device_id', '-timestamp'], name='sensors_sen_device__b6d36a_idx')],
            },
        ),
    ]
