# Generated by Django 4.2.7 on 2025-11-23 13:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('weapon_type', models.CharField(choices=[('rifle', 'Rifle'), ('shotgun', 'Shotgun'), ('handgun', 'Handgun'), ('bow', 'Bow')], max_length=20)),
                ('current_location', models.CharField(default='Unknown', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('sound_level', models.FloatField(help_text='Sound level in dB')),
                ('vibration_level', models.FloatField(help_text='Vibration level in Hz')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('weapon_used', models.CharField(choices=[('rifle', 'Rifle'), ('shotgun', 'Shotgun'), ('handgun', 'Handgun'), ('bow', 'Bow')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='hunters.hunter')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
